-- MySQL Script generated by MySQL Workbench
-- Sat May 13 10:16:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- Schema segurosJS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema segurosJS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `segurosJS` DEFAULT CHARACTER SET utf8 ;
USE `segurosJS` ;

-- -----------------------------------------------------
-- Table `segurosJS`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `segurosJS`.`categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `descripciónCategoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;

USE `segurosJS` ;

-- -----------------------------------------------------
-- Table `segurosJS`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `segurosJS`.`administrador` (
  `usuarioAdmin` VARCHAR(45) NOT NULL,
  `claveAdmin` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuarioAdmin`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `segurosJS`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `segurosJS`.`cliente` (
  `cedulaCliente` VARCHAR(45) NOT NULL,
  `nombreCliente` VARCHAR(45) NOT NULL,
  `usuarioCliente` VARCHAR(45) NOT NULL,
  `claveCliente` VARCHAR(45) NOT NULL,
  `telefonoCliente` VARCHAR(45) NOT NULL,
  `correoCliente` VARCHAR(45) NOT NULL,
  `numeroTarjeta` VARCHAR(45) NOT NULL,
  `vencimientoTarjeta` VARCHAR(45) NOT NULL,
  `cvcTarjeta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuarioCliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `segurosJS`.`cobertura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `segurosJS`.`cobertura` (
  `idCobertura` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcionCobertura` VARCHAR(45) NOT NULL,
  `costoMinimoCobertura` DOUBLE NOT NULL,
  `costoPorcentualCobertura` DOUBLE NOT NULL,
  `categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idCobertura`),
  INDEX `fk_cobertura_categoria1_idx` (`categoria_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_cobertura_categoria1`
    FOREIGN KEY (`categoria_idCategoria`)
    REFERENCES `segurosJS`.`categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `segurosJS`.`poliza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `segurosJS`.`poliza` (
  `idPoliza` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numeroPoliza` VARCHAR(45) NOT NULL,
  `añoPoliza` VARCHAR(45) NOT NULL,
  `plazoPoliza` VARCHAR(45) NOT NULL,
  `valorPoliza` DOUBLE NOT NULL,
  `clientePoliza` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPoliza`),
  CONSTRAINT `fk_poliza_cliente`
    FOREIGN KEY (`clientePoliza`)
    REFERENCES `segurosJS`.`cliente` (`usuarioCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `segurosJS`.`cobertura_poliza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `segurosJS`.`cobertura_poliza` (
  `Poliza_idPoliza` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Cobertura_idCobertura` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Poliza_idPoliza`, `Cobertura_idCobertura`),
  INDEX `fk_cobertura_poliza_cobertura1_idx` (`Cobertura_idCobertura` ASC) VISIBLE,
  INDEX `fk_cobertura_poliza_poliza1_idx` (`Poliza_idPoliza` ASC) VISIBLE,
  CONSTRAINT `fk_cobertura_poliza_cobertura1`
    FOREIGN KEY (`Cobertura_idCobertura`)
    REFERENCES `segurosJS`.`cobertura` (`idCobertura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cobertura_poliza_poliza1`
    FOREIGN KEY (`Poliza_idPoliza`)
    REFERENCES `segurosJS`.`poliza` (`idPoliza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `segurosJS`.`vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `segurosJS`.`vehiculo` (
  `idVehiculo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `marcaVehiculo` VARCHAR(45) NOT NULL,
  `modeloVehiculo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVehiculo`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `segurosJS`.`vehiculo_poliza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `segurosJS`.`vehiculo_poliza` (
  `Poliza_idPoliza` INT UNSIGNED NOT NULL,
  `Vehiculo_idVehiculo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Poliza_idPoliza`, `Vehiculo_idVehiculo`),
  INDEX `fk_vehiculo_poliza_vehiculo1_idx` (`Vehiculo_idVehiculo` ASC) VISIBLE,
  INDEX `fk_vehiculo_poliza_poliza1_idx` (`Poliza_idPoliza`
  ASC) VISIBLE,
  CONSTRAINT `fk_vehiculo_poliza_vehiculo1`
    FOREIGN KEY (`Vehiculo_idVehiculo`)
    REFERENCES `segurosJS`.`vehiculo` (`idVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehiculo_poliza_poliza1`
    FOREIGN KEY (`Poliza_idPoliza`)
    REFERENCES `segurosJS`.`poliza` (`idPoliza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
